version: '3.7'

services:
  spark:
    image: jupyter/pyspark-notebook:63d0df23b673
    container_name: spark
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    environment:
      GRANT_SUDO: 'yes'
      SCHEMA_REGISTRY_URL: $SCHEMA_REGISTRY_URL
      SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: $SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
      BROKER_URL: $BROKER_URL
      CONFLUENT_KAFKA_API_KEY: $CONFLUENT_KAFKA_API_KEY
      CONFLUENT_KAFKA_API_SECRET: $CONFLUENT_KAFKA_API_SECRET
      SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
    volumes:
      - ./:/home/jovyan/work
